#ifndef CONNECTIVE_HPP
#define	CONNECTIVE_HPP

#include "language.hpp"

enum Connective
{
    NEGATION = NEGATION_CHAR, CONJUNCTION = CONJUNCTION_CHAR, DISJUNCTION = DISJUNCTION_CHAR, IMPLICATION = IMPLICATION_CHAR, EQUIVALENCE = EQUIVALENCE_CHAR
};

#endif	/* CONNECTIVE_HPP */

