.TH PL 1 "2014-02-27"

.SH NAME
pl - handle formulas of propositional logic

.SH SYNOPSIS \" Todo: Unimplemented options synopsis.
.B pl [\fB-io\fI notation] [\fB-l\fI language] [\fB-f\fI file]

.SH DESCRIPTION \" Todo: Description
Description here.

.SH OPTIONS \" Todo: Unimplemented options description.
.TP
\fB-i\fI notation
Expect specified input notation which can be\fI prefix, infix, postfix.\fR The\fI infix\fR is expected by default.

.SH EXAMPLE \" Todo: Unimplemented parameter examples.
.TP
echo "-(A+B)" | pl -o prefix
Outputs "-+AB".

.SH AUTHOR
Jan Švajcr (svajcjan@fit.cvut.cz)
