.Dd March 25, 2014
.Dt PL 1
.Os Linux
.Sh NAME
.Nm pl
.Nd handle formulas of propositional logic
.Sh SYNOPSIS
.Nm
.Op Fl AefiloP
.Sh DESCRIPTION
The pl utility implements the rudimentary algorithms of propositional logic. By default, it parses the standard input as propositional formulas, reports syntax errors, and exits. Other actions, as proof or axiom validation, can be specified via the options.
.Ss Language
The latin capital A—Z are considered atomic propositions. This means we are reducing the possible complexity of formulas to 26 propositional variables, which is enough for our purposes.
.Pp
The following table describes how the propositional connectives are expressed in ASCII, words, and TeX output.
.Pp
.Bl -column "Connective" "ASCII" "words" "TeX" -compact
.It Em "Connective	ASCII	words	TeX"
.It Li negation Ta - Ta not Ta neg
.It Li conjunction Ta . Ta and Ta wedge
.It Li disjunction Ta + Ta or Ta vee
.It Li implication Ta > Ta implies Ta rightarrow
.It Li equivalence Ta = Ta iff Ta leftrightarrow
.El
.Ss Input
Three types of input syntax are supported: prefix, infix and postfix. Only the ASCII form of connectives is recognized. With binary operations in infix, parentheses are required so e.g. 'A+—B' is not a valid formula, but '(A+—B)' is. White space is silently ignored, except newlines, which mark the end of one formula and the beginning of another one.
.Ss Output
Three types of input syntax are supported: prefix, infix and postfix. The connectives can be output as ASCII, words, or TeX, as described in the table above. The ASCII output can be piped back into pl as input.
.Ss Options
The options are as follows.
.Bl -tag -width Fl
.It Fl A
Check whether each formula is a Hilbert axiom.
.It Fl e
Echo parsed formulas.
.It Fl f Ar file
Read formulas from the file instead of standard input.
.It Fl i Ar notation
Expect specified input notation. Can be 'infix', 'prefix' or 'postfix'. By default, 'infix' is expected.
.It Fl l Ar language
Use specified output language. Can be 'ascii', 'words' or 'tex'. By default, 'ascii' is used.
.It Fl o Ar notation
Use specified output notation. Can be 'infix', 'prefix' or 'postfix'. By default, 'infix' is used.
.It Fl P
Check whether the sequence of formulas is a valid Hilbert proof.
.El
.Sh EXAMPLES
.Bl -tag -width Fl
.It Outputs \&"-+AB\&"
echo \&"-(A+B)\&" | pl -o prefix
.El
.Sh HISTORY
Written for academic purposes in 2014.
.Sh AUTHORS
Written by
.An Jan Švajcr Mt svajcjan@fit.cvut.cz
